openapi: 3.0.0
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Balance Management
    description: 잔액 충전/조회 API
  - name: Order
    description: 주문/결제 API
  - name: Product
    description: 상품 조회 API
  - name: Coupon
    description: 선착순 쿠폰 발급/조회 API
paths:
  /api/v1/order:
    post:
      tags:
        - Order
      summary: 주문 생성
      description: 여러 상품을 동시에 주문하고, 결제(잔액 차감/쿠폰 사용)를 진행합니다.
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
        required: true
      responses:
        '200':
          description: 주문/결제 성공
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseOrderResponse'
        '400':
          description: 요청 데이터 오류 or 재고 부족 or 잔액 부족
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseOrderResponse'
        '500':
          description: 서버 오류
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseOrderResponse'
  /api/v1/coupons/issue:
    post:
      tags:
        - Coupon
      summary: 쿠폰 발급
      description: 선착순 쿠폰을 발급. 쿠폰 재고가 소진되면 발급이 불가합니다.
      operationId: issueCoupon
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CouponIssueRequest'
        required: true
      responses:
        '200':
          description: 발급 성공
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseUserCouponResponse'
        '400':
          description: 이미 발급됨 or 재고 소진
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseUserCouponResponse'
        '500':
          description: 서버 오류
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseUserCouponResponse'
  /api/v1/balance/charge:
    post:
      tags:
        - Balance Management
      summary: 잔액 충전
      description: 사용자 잔액을 일정 금액만큼 충전합니다.
      operationId: charge
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalanceChargeRequest'
        required: true
      responses:
        '200':
          description: 충전 성공
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseBalanceChargeResponse'
        '400':
          description: 잘못된 요청
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseBalanceChargeResponse'
        '500':
          description: 서버 오류
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseBalanceChargeResponse'
  /api/v1/products:
    get:
      tags:
        - Product
      summary: 상품 목록 조회
      description: 판매 중인 상품 목록을 페이징 및 키워드 검색으로 조회합니다.
      operationId: getProducts
      parameters:
        - name: page
          in: query
          description: 페이지 번호
          required: false
          schema:
            type: integer
            format: int32
            default: 1
            minimum: 1
        - name: size
          in: query
          description: 페이지 크기
          required: false
          schema:
            type: integer
            format: int32
            default: 10
            minimum: 1
        - name: keyword
          in: query
          description: 상품명 검색어
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 조회 성공
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseProductListResponse'
        '400':
          description: 검색 파라미터 오류
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseProductListResponse'
        '500':
          description: 서버 오류
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseProductListResponse'
  /api/v1/products/top-sellers:
    get:
      tags:
        - Product
      summary: 상위 판매 상품 조회
      description: 최근 N일 간 가장 많이 팔린 상위 상품들을 조회합니다.
      operationId: getTopSellers
      parameters:
        - name: days
          in: query
          description: 며칠간 판매량 기준 (기본값 3)
          required: false
          schema:
            type: integer
            format: int32
            default: 3
            minimum: 3
      responses:
        '200':
          description: 조회 성공
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseTopSellerResponse'
        '400':
          description: 조회 파라미터 오류
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseTopSellerResponse'
        '500':
          description: 서버 오류
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseTopSellerResponse'
  /api/v1/coupons/users/{userId}:
    get:
      tags:
        - Coupon
      summary: 사용자 보유 쿠폰 조회
      description: 해당 유저가 현재 보유 중인 모든 쿠폰을 조회합니다.
      operationId: getUserCoupons
      parameters:
        - name: userId
          in: path
          description: 사용자 식별자
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: 조회 성공
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseUserCouponListResponse'
        '400':
          description: 존재하지 않는 사용자
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseUserCouponListResponse'
        '500':
          description: 서버 오류
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseUserCouponListResponse'
  /api/v1/balance/{userId}:
    get:
      tags:
        - Balance Management
      summary: 잔액 조회
      description: 사용자의 현재 잔액을 조회합니다.
      operationId: getBalance
      parameters:
        - name: userId
          in: path
          description: 사용자 식별자
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: 조회 성공
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseBalanceResponse'
        '400':
          description: 잘못된 요청
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseBalanceResponse'
        '500':
          description: 서버 오류
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebApiResponseBalanceResponse'
components:
  schemas:
    OrderItem:
      type: object
      properties:
        quantity:
          type: integer
          format: int64
          minimum: 1
        productId:
          type: integer
          format: int64
          minimum: 1
    OrderRequest:
      type: object
      description: 주문 생성 요청 바디
      properties:
        userId:
          type: integer
          format: int64
          minimum: 1
        couponId:
          type: integer
          format: int64
          minimum: 1
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
      required:
        - orderItems
        - userId
    ErrorMessage:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        data: { }
    OrderResponse:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        status:
          type: string
        totalAmount:
          type: integer
          format: int64
        discountAmount:
          type: integer
          format: int64
        paidAmount:
          type: integer
          format: int64
        paymentId:
          type: integer
          format: int64
        paymentStatus:
          type: string
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        createdAt:
          type: string
          format: date-time
    WebApiResponseOrderResponse:
      type: object
      properties:
        result:
          type: string
          description: 응답 상태
          enum:
            - SUCCESS
            - ERROR
        data:
          $ref: '#/components/schemas/OrderResponse'
          description: 응답 데이터
        error:
          $ref: '#/components/schemas/ErrorMessage'
          description: 에러 메세지
    CouponIssueRequest:
      type: object
      description: 쿠폰 발급 요청 바디
      properties:
        userId:
          type: integer
          format: int64
          minimum: 1
        couponId:
          type: integer
          format: int64
          minimum: 1
        issuedAt:
          type: string
          format: date-time
      required:
        - couponId
        - issuedAt
        - userId
    UserCouponResponse:
      type: object
      properties:
        userCouponId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        couponId:
          type: integer
          format: int64
        issuedAt:
          type: string
          format: date-time
        status:
          type: string
    WebApiResponseUserCouponResponse:
      type: object
      properties:
        result:
          type: string
          description: 응답 상태
          enum:
            - SUCCESS
            - ERROR
        data:
          $ref: '#/components/schemas/UserCouponResponse'
          description: 응답 데이터
        error:
          $ref: '#/components/schemas/ErrorMessage'
          description: 에러 메세지
    BalanceChargeRequest:
      type: object
      description: 잔액 충전 요청 바디
      properties:
        userId:
          type: integer
          format: int64
          minimum: 1
        amount:
          type: integer
          format: int64
          minimum: 100
      required:
        - amount
        - userId
    BalanceChargeResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        balance:
          type: integer
          format: int64
    WebApiResponseBalanceChargeResponse:
      type: object
      properties:
        result:
          type: string
          description: 응답 상태
          enum:
            - SUCCESS
            - ERROR
        data:
          $ref: '#/components/schemas/BalanceChargeResponse'
          description: 응답 데이터
        error:
          $ref: '#/components/schemas/ErrorMessage'
          description: 에러 메세지
    PageInfo:
      type: object
      properties:
        currentPage:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        totalItems:
          type: integer
          format: int64
    ProductInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: integer
          format: int64
        stock:
          type: integer
          format: int64
    ProductListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductInfo'
        pageInfo:
          $ref: '#/components/schemas/PageInfo'
    WebApiResponseProductListResponse:
      type: object
      properties:
        result:
          type: string
          description: 응답 상태
          enum:
            - SUCCESS
            - ERROR
        data:
          $ref: '#/components/schemas/ProductListResponse'
          description: 응답 데이터
        error:
          $ref: '#/components/schemas/ErrorMessage'
          description: 에러 메세지
    TopSellerInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        totalSold:
          type: integer
          format: int64
    TopSellerResponse:
      type: object
      properties:
        periodDays:
          type: integer
          format: int32
        topSellers:
          type: array
          items:
            $ref: '#/components/schemas/TopSellerInfo'
    WebApiResponseTopSellerResponse:
      type: object
      properties:
        result:
          type: string
          description: 응답 상태
          enum:
            - SUCCESS
            - ERROR
        data:
          $ref: '#/components/schemas/TopSellerResponse'
          description: 응답 데이터
        error:
          $ref: '#/components/schemas/ErrorMessage'
          description: 에러 메세지
    UserCouponInfo:
      type: object
      properties:
        userCouponId:
          type: integer
          format: int64
        couponId:
          type: integer
          format: int64
        couponName:
          type: string
        amount:
          type: integer
          format: int64
        isUsed:
          type: boolean
        expiredAt:
          type: string
          format: date-time
    UserCouponListResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        coupons:
          type: array
          items:
            $ref: '#/components/schemas/UserCouponInfo'
    WebApiResponseUserCouponListResponse:
      type: object
      properties:
        result:
          type: string
          description: 응답 상태
          enum:
            - SUCCESS
            - ERROR
        data:
          $ref: '#/components/schemas/UserCouponListResponse'
          description: 응답 데이터
        error:
          $ref: '#/components/schemas/ErrorMessage'
          description: 에러 메세지
    BalanceResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        balance:
          type: integer
          format: int64
    WebApiResponseBalanceResponse:
      type: object
      properties:
        result:
          type: string
          description: 응답 상태
          enum:
            - SUCCESS
            - ERROR
        data:
          $ref: '#/components/schemas/BalanceResponse'
          description: 응답 데이터
        error:
          $ref: '#/components/schemas/ErrorMessage'
          description: 에러 메세지
